- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/coder/gateway/sdk/TemplateIconDownloader.kt
com.intellij.ui.paint.alignToInt was made internal so the easiest way to maintain backwards compatibility seems to be to just copy it.
Closes https://github.com/coder/jetbrains-coder/issues/262.
Tested manually on Linux and Windows with the latest Gateway EAP (232.8296.17) and the previous version (231.8109.172).
> Add support for Gateway 2023.2

- build.gradle.kts
- gradle.properties
- src/main/kotlin/com/coder/gateway/views/CoderGatewayRecentWorkspaceConnectionsView.kt
If you run the latest plugin on Gateway 231 you get an error about DeployWithDownload being void when the IDE is not already installed.
Reverting the platform version back to 231 makes the plugin work on both 231 and 232 (the current EAP).
Honestly I do not understand why this is necessary as the API here does not appear to have changed at all.
Upon doing some research though it appears that the platform version should match the "since build" version so I downgraded further.  It seems `minimumWidth` and `maximumWidth` are not available in that version so our plugin is currently broken there as well.  This is fixed by using `size` instead.
I think normally the plugin verifier would catch these things and I tried getting it working by specifying the versions to check but it seems to be …
> Downgrade platformVersion

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspacesStepView.kt
We set it when connecting so this results in no CLI being available (for example if you go back and select a different or even the same workspace).
Fixes #277.
> Do not remove CLI when going back to workspaces view

- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspacesStepView.kt
- src/main/resources/messages/CoderGatewayBundle.properties
Since this help text contains markup which does not work in the table I added a new comment field underneath the URL input to place the error along with the help instead of trying to put it directly in the table.  I moved the other errors there too to be consistent and in the table it will tell you to look up for the details.
I also swapped `code-oss` for `v2` in two existing URLs since it seems that is the correct slug now.
Closes https://github.com/coder/jetbrains-coder/issues/251.
> Add extra help for certificate errors

- src/main/resources/version/CoderSupportedVersions.properties
We recently released a 2.0 which added a warning
> fix: remove version warning for 2.x releases

- gradle.properties
- src/main/resources/version/CoderSupportedVersions.properties
No reason to change the min version at this point!
> chore: changelog + revert min version to fix semver test

- README.md
- src/main/kotlin/com/coder/gateway/CoderGatewayConnectionProvider.kt
- src/main/kotlin/com/coder/gateway/CoderRemoteConnectionHandle.kt
- src/main/kotlin/com/coder/gateway/WorkspaceParams.kt
- src/main/kotlin/com/coder/gateway/models/CoderWorkspacesWizardModel.kt
- src/main/kotlin/com/coder/gateway/models/WorkspaceAndAgentStatus.kt
- src/main/kotlin/com/coder/gateway/sdk/CoderRestClientService.kt
- src/main/kotlin/com/coder/gateway/views/CoderGatewayRecentWorkspaceConnectionsView.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderLocateRemoteProjectStepView.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspacesStepView.kt
- src/main/resources/messages/CoderGatewayBundle.properties
- src/test/groovy/CoderRemoteConnectionHandleTest.groovy
I created a new class to share some common connection code between the step-based wizard flow and the link-based flow.  I think we can share more things as we go on but I did not try too hard to combine more code until the shape of the link-based flow solidifies some more.  So there is some duplication like the authentication loop, logging in the CLI, etc, that cannot be easily shared without some refactoring.
It might even end up being that we just always launch into the wizard flow but if some parameters are already set we automatically skip through certain steps.  Not sure.
This is a first pass, right now you have to specify most of the parameters yourself (aside from deployment URL and token which, if missing, will trigger prompts to the user).
There are a few todos that I want to …
> Handle Gateway links

- .github/workflows/build.yml
- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/coder/gateway/CoderGatewayConnectionProvider.kt
- src/main/kotlin/com/coder/gateway/CoderSettingsConfigurable.kt
- src/main/kotlin/com/coder/gateway/sdk/CoderCLIManager.kt
- src/main/kotlin/com/coder/gateway/sdk/CoderRestClientService.kt
- src/main/kotlin/com/coder/gateway/services/CoderSettingsState.kt
- src/main/kotlin/com/coder/gateway/views/CoderGatewayRecentWorkspaceConnectionsView.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspacesStepView.kt
- src/main/resources/messages/CoderGatewayBundle.properties
- src/test/fixtures/outputs/append-blank-newlines.conf
- src/test/fixtures/outputs/append-blank.conf
- src/test/fixtures/outputs/append-no-blocks.conf
- src/test/fixtures/outputs/append-no-newline.conf
- src/test/fixtures/outputs/append-no-related-blocks.conf
- src/test/fixtures/outputs/header-command-windows.conf
- src/test/fixtures/outputs/header-command.conf
- src/test/fixtures/outputs/multiple-workspaces.conf
- src/test/fixtures/outputs/replace-end-no-newline.conf
- src/test/fixtures/outputs/replace-end.conf
- src/test/fixtures/outputs/replace-middle-ignore-unrelated.conf
- src/test/fixtures/outputs/replace-middle.conf
- src/test/fixtures/outputs/replace-only.conf
- src/test/fixtures/outputs/replace-start.conf
- src/test/groovy/CoderCLIManagerTest.groovy
- src/test/groovy/CoderRestClientTest.groovy
Closes https://github.com/coder/jetbrains-coder/issues/293
> Add header command setting

- src/main/kotlin/com/coder/gateway/CoderGatewayConnectionProvider.kt
- src/main/kotlin/com/coder/gateway/models/WorkspaceAgentModel.kt
- src/main/kotlin/com/coder/gateway/sdk/v2/models/Workspace.kt
- src/test/groovy/CoderCLIManagerTest.groovy
- src/test/groovy/CoderGatewayConnectionProviderTest.groovy
- src/test/groovy/CoderWorkspacesStepViewTest.groovy
- src/test/groovy/DataGen.groovy
Part of https://github.com/coder/jetbrains-coder/issues/292
This will let you set the agent by either ID or name.  If both are set then the name is ignored.
> Support agent ID parameter

- src/main/kotlin/com/coder/gateway/CoderGatewayConnectionProvider.kt
- src/main/kotlin/com/coder/gateway/models/WorkspaceAgentModel.kt
- src/main/kotlin/com/coder/gateway/sdk/CoderRestClientService.kt
- src/main/kotlin/com/coder/gateway/sdk/v2/CoderV2RestFacade.kt
- src/main/kotlin/com/coder/gateway/sdk/v2/models/Workspace.kt
- src/main/kotlin/com/coder/gateway/views/CoderGatewayRecentWorkspaceConnectionsView.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspacesStepView.kt
- src/test/groovy/CoderCLIManagerTest.groovy
- src/test/groovy/CoderGatewayConnectionProviderTest.groovy
- src/test/groovy/CoderRestClientTest.groovy
- src/test/groovy/CoderWorkspacesStepViewTest.groovy
- src/test/groovy/DataGen.groovy
I just copied the way the Coder CLI does it.
This way, it will not drop hosts when it reconfigures SSH if those hosts happen to be off.  I am not sure if the agents missing from the workspaces response is intended, but since the CLI does it this way I assume it is intentional.
I tested both connection flows and both worked first try, which has me extremely suspicious but I guess the change is pretty straightforward.
Fixes https://github.com/coder/jetbrains-coder/issues/290
> Fix missing agents when workspaces are off

- gradle.properties
- src/main/kotlin/com/coder/gateway/CoderGatewayConnectionProvider.kt
- src/main/kotlin/com/coder/gateway/CoderSettingsConfigurable.kt
- src/main/kotlin/com/coder/gateway/sdk/CoderCLIManager.kt
- src/main/kotlin/com/coder/gateway/sdk/CoderRestClientService.kt
- src/main/kotlin/com/coder/gateway/services/CoderSettingsState.kt
- src/main/kotlin/com/coder/gateway/views/CoderGatewayRecentWorkspaceConnectionsView.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspacesStepView.kt
- src/main/resources/messages/CoderGatewayBundle.properties
- src/test/groovy/CoderCLIManagerTest.groovy
- src/test/groovy/CoderRestClientTest.groovy
adding options to support mtls with the coder server.  This supports adding PEM certs and keys to the tls requests, and also supports adding a CA cert to the trust store.  Also allowing for an alternate hostname that may appear in the certs which is useful for testing or for non-standard cert usage.
This is similar to the change for the vscode plugin: https://github.com/coder/vscode-coder/issues/126
I am not terribly familiar with kotlin or java so let me know if there are non-idiomatic things you want changed.
> feat: add configuration options to support mtls

- src/main/kotlin/com/coder/gateway/sdk/CoderCLIManager.kt
The login phase of the JetBrains Coder plugin involves downloading a fresh CLI binary from the control plane. However, if the control plane is located behind a VPN or protected by Cloudflare, it requires passing relevant tokens to the download request to ensure a successful download. To handle this, JetBrains Coder introduces the concept of "header commands" as a means of adding these tokens.
This pull request addresses the need to support header commands by utilizing them  when downloading the CLI binary
1. **Added Support for Header Commands:** This PR includes the necessary changes to enable the use of header commands during the CLI binary download process.
Enabling header commands support for CLI binary downloads is crucial for ensuring the seamless operation of the JetBrains Coder …
> Adding Header Commands To The Download CLI phase

- src/main/kotlin/com/coder/gateway/sdk/CoderCLIManager.kt
- src/test/fixtures/outputs/append-blank-newlines.conf
- src/test/fixtures/outputs/append-blank.conf
- src/test/fixtures/outputs/append-no-blocks.conf
- src/test/fixtures/outputs/append-no-newline.conf
- src/test/fixtures/outputs/append-no-related-blocks.conf
- src/test/fixtures/outputs/header-command-windows.conf
- src/test/fixtures/outputs/header-command.conf
- src/test/fixtures/outputs/multiple-workspaces.conf
- src/test/fixtures/outputs/replace-end-no-newline.conf
- src/test/fixtures/outputs/replace-end.conf
- src/test/fixtures/outputs/replace-middle-ignore-unrelated.conf
- src/test/fixtures/outputs/replace-middle.conf
- src/test/fixtures/outputs/replace-only.conf
- src/test/fixtures/outputs/replace-start.conf
Having `HostName` causes errors in Gateway about the host not being found even though it seems to work in the end...but all those (many, many) errors make the logs noisy and maybe this is causing some instability in some cases.
I have no idea why Gateway is trying to connect to `HostName` when there is a `ProxyCommand` but it smells like a bug.
For now I removed `HostName` and there are no more errors.  It was just copied from how the Coder CLI does things so hopefully it is not actually required somehow because I have no idea why it was included in the first place.  Everything works for me without it.
> Remove HostName from SSH config

- src/main/kotlin/com/coder/gateway/models/RecentWorkspaceConnection.kt
From what I understand when you use BaseState you are supposed to use delegation.  Something must have changed because this code used to work just as it was, but now it seems without delegation the properties are ignored and we were getting recent entries that were blank (looked like this: `<RecentWorkspaceConnection />`).
It does not appear possible to use delegation with a data class so I had to make a separate constructor. 
Closes https://github.com/coder/jetbrains-coder/issues/304
> Fix recently opened workspaces not being saved

- src/main/kotlin/com/coder/gateway/sdk/CoderCLIManager.kt
To create missing .ssh folder `Files.createDirectories(...)` is used which always tries to create a directory.
In some cases, especially when .ssh is actually a symbolic link this results in an uncatched `FileAlreadyExistsException` being thrown.
This PR mitigates this by replacing the folder creation with `File#mkdirs()` which checks the existence of the path before doing anything.
> Fix error with specific ssh configurations

- src/main/kotlin/com/coder/gateway/sdk/BaseCoderRestClient.kt
- src/main/kotlin/com/coder/gateway/sdk/v2/models/Response.kt
- src/test/kotlin/com/coder/gateway/CoderGatewayConnectionProviderTest.kt
- src/test/kotlin/com/coder/gateway/sdk/BaseCoderRestClientTest.kt
- src/test/kotlin/com/coder/gateway/sdk/DataGen.kt
Closes #350 
This is mostly test code.  I am not really sure it is even worth all the effort since this basically just checks we call the endpoints we call, which seems like it might just force us to update two places if we need to fix anything and not actually catch any bugs.  But maybe it is better than nothing.
> Stop workspace before updating

- src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt
- src/main/kotlin/com/coder/gateway/util/Escape.kt
- src/test/fixtures/outputs/header-command-windows.conf
- src/test/fixtures/outputs/header-command.conf
- src/test/kotlin/com/coder/gateway/cli/CoderCLIManagerTest.kt
- src/test/kotlin/com/coder/gateway/util/EscapeTest.kt
Fixes https://github.com/coder/jetbrains-coder/issues/338.
The problem was that if your header command was something like `auth --url=$CODER_URL`, it would get expanded as part of executing the proxy command and you end up with `auth --url=` since `CODER_URL` is not set.
We want to pass it literally to the binary so that it can then be expanded in the binary when it executes the header command, since the binary will set `CODER_URL` when spawning.
An alternative would be to set `CODER_URL` when the proxy command is spawned, but I am not sure we can as I think it would be using the current process environment (via that SSHJ library I think).  Maybe there is a way to mutate the current environment, but a quick look says no.
> Prevent early variable expansion in header command

- CHANGELOG.md
- src/main/kotlin/com/coder/gateway/CoderSettingsConfigurable.kt
- src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt
- src/main/kotlin/com/coder/gateway/services/CoderSettingsState.kt
- src/main/kotlin/com/coder/gateway/settings/CoderSettings.kt
- src/main/resources/messages/CoderGatewayBundle.properties
- src/test/fixtures/outputs/disable-autostart.conf
- src/test/fixtures/outputs/no-disable-autostart.conf
- src/test/kotlin/com/coder/gateway/cli/CoderCLIManagerTest.kt
- src/test/kotlin/com/coder/gateway/settings/CoderSettingsTest.kt
On macOS this is checked by default for 2.5.0 and above.
Closes https://github.com/coder/jetbrains-coder/issues/365
> Add the ability to disable autostart

- gradle.properties
- src/main/kotlin/com/coder/gateway/CoderGatewayConnectionProvider.kt
- src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspaceStepView.kt
- src/test/kotlin/com/coder/gateway/cli/CoderCLIManagerTest.kt
I really have no idea what I am doing, but this seems to work...
If the the `jetbrains-gateway://` URL handler request is missing `ide_product_code`, `ide_build_number`, i`de_path_on_host` (or `ide_download_link`), or `folder` then we will open up a dialog that goes through the ide selection box (step 2 from normal UI flow).
Any feedback is most welcome!
> add popup diaglog for missing IDE data on url handler

- src/main/kotlin/com/coder/gateway/CoderSettingsConfigurable.kt
- src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt
- src/main/kotlin/com/coder/gateway/settings/CoderSettings.kt
- src/main/resources/messages/CoderGatewayBundle.properties
- src/test/fixtures/outputs/extra-config.conf
- src/test/kotlin/com/coder/gateway/cli/CoderCLIManagerTest.kt
- src/test/kotlin/com/coder/gateway/settings/CoderSettingsTest.kt
Closes https://github.com/coder/jetbrains-coder/issues/354
It parallels `--ssh-config-options` from the CLI.
> Add extra SSH options setting

- src/main/kotlin/com/coder/gateway/util/Headers.kt
- src/test/kotlin/com/coder/gateway/util/HeadersTest.kt
- Do not include stderr.
- Allow no output.
Closes #404
> Bring parity with cli to header command

- CHANGELOG.md
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspacesStepView.kt
Before it was (probably on accident) just duplicating the status column.
Now it looks like this:
> Make version column display outdated status

- src/main/kotlin/com/coder/gateway/CoderRemoteConnectionHandle.kt
- src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspaceProjectIDEStepView.kt
- src/test/fixtures/outputs/append-blank-newlines.conf
- src/test/fixtures/outputs/append-blank.conf
- src/test/fixtures/outputs/append-no-blocks.conf
- src/test/fixtures/outputs/append-no-newline.conf
- src/test/fixtures/outputs/append-no-related-blocks.conf
- src/test/fixtures/outputs/disable-autostart.conf
- src/test/fixtures/outputs/extra-config.conf
- src/test/fixtures/outputs/header-command-windows.conf
- src/test/fixtures/outputs/header-command.conf
- src/test/fixtures/outputs/multiple-workspaces.conf
- src/test/fixtures/outputs/no-disable-autostart.conf
- src/test/fixtures/outputs/no-report-usage.conf
- src/test/fixtures/outputs/replace-end-no-newline.conf
- src/test/fixtures/outputs/replace-end.conf
- src/test/fixtures/outputs/replace-middle-ignore-unrelated.conf
- src/test/fixtures/outputs/replace-middle.conf
- src/test/fixtures/outputs/replace-only.conf
- src/test/fixtures/outputs/replace-start.conf
- src/test/fixtures/outputs/report-usage.conf
- src/test/kotlin/com/coder/gateway/cli/CoderCLIManagerTest.kt
This adds a new `getBackgroundHostName()` func that is intended to be used for all SSH connections that are not the main IDE connection. This prevents background admin actions using SSH to trigger usage tracking for the workspace.
> chore: use background hostname for admin tasks

- CHANGELOG.md
- src/main/kotlin/com/coder/gateway/CoderRemoteConnectionHandle.kt
- src/main/kotlin/com/coder/gateway/views/CoderGatewayRecentWorkspaceConnectionsView.kt
**Edit**: we changed the flow, links do show but are disabled if the workspace is in a non-starting pending state, and we started the workspace automatically negating the need to even have the manual controls
Previously recent workspaces had a status icon which looked a bit like a button to push, and the start workspace button could be confused as the cta to open a project.
Now the project links in recent projects only display once the workspace is running and ready to accept connections, and the confusing icon has been removed.
I think this flow is pretty clear, but people used to just clicking the link might freak out when they don't see their links or be frustrated they need to press two buttons.
An alternative option could be to remove the workspace start button entirely, since …
> revise recent projects flow to be less confusing

- CHANGELOG.md
- src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt
- src/test/fixtures/outputs/append-blank-newlines.conf
- src/test/fixtures/outputs/append-blank.conf
- src/test/fixtures/outputs/append-no-blocks.conf
- src/test/fixtures/outputs/append-no-newline.conf
- src/test/fixtures/outputs/append-no-related-blocks.conf
- src/test/fixtures/outputs/disable-autostart.conf
- src/test/fixtures/outputs/extra-config.conf
- src/test/fixtures/outputs/header-command-windows.conf
- src/test/fixtures/outputs/header-command.conf
- src/test/fixtures/outputs/log-dir.conf
- src/test/fixtures/outputs/multiple-workspaces.conf
- src/test/fixtures/outputs/no-disable-autostart.conf
- src/test/fixtures/outputs/no-report-usage.conf
- src/test/fixtures/outputs/replace-end-no-newline.conf
- src/test/fixtures/outputs/replace-end.conf
- src/test/fixtures/outputs/replace-middle-ignore-unrelated.conf
- src/test/fixtures/outputs/replace-middle.conf
- src/test/fixtures/outputs/replace-only.conf
- src/test/fixtures/outputs/replace-start.conf
This fixes an issue where you have `CODER_URL` in your environment but then connect to a different URL.  The plugin will configure the settings file, but the cli will ignore it in favor of the environment variable.  The flag is always preferred, so setting that ensures we use the right URL.
Unit tests show it gets added at least, but sure would be nice if we could test the flow.  For now I manually set `CODER_URL` to something bogus when launching Gateway (like http://localhost:1234) then added a new connection as normal to dev.coder.com.
> Set --url in SSH config

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/coder/gateway/util/Escape.kt
- src/test/fixtures/outputs/url.conf
- src/test/kotlin/com/coder/gateway/cli/CoderCLIManagerTest.kt
- src/test/kotlin/com/coder/gateway/util/EscapeTest.kt
> fix: escape ampersand and question mark in ProxyCommand

- gradle.properties
> Add support for version 2024.3

- .github/workflows/build.yml
- .github/workflows/release.yml
The rest (publishing and uploading an artifact) is a todo.
> [toolbox] Build in CI

- src/main/kotlin/com/coder/gateway/CoderRemoteEnvironment.kt
- src/main/kotlin/com/coder/gateway/CoderRemoteProvider.kt
- src/main/kotlin/com/coder/gateway/models/WorkspaceAndAgentStatus.kt
- src/main/kotlin/com/coder/gateway/sdk/v2/models/Workspace.kt
- src/main/kotlin/com/coder/gateway/views/CoderPage.kt
- src/test/kotlin/com/coder/gateway/sdk/DataGen.kt
You can now start, stop, and update workspaces.  Since you can start workspaces yourself now, I marked non-ready states as unreachable, which prevents JetBrains from overriding with their own text ("disconnected" and "connected").  So now you will be able to see "stopped", "starting", and so on, which is nice.  For the ready states you will still see "disconnected" or "connected" unfortunately.  Ideally this would be displayed separately from the workspace state.  This also means you have two clicks instead of one to connect to a workspace, but I felt like it was worth the tradeoff to (mostly) see the actual workspace state, and it does match the current Gateway flow.  If we can separate the states visually then we can bring back the one-click behavior.
Weirdly, you can still press …
> [toolbox] Add workspace actions

- src/main/kotlin/com/coder/gateway/sdk/CoderRestClient.kt
- src/main/kotlin/com/coder/gateway/views/CoderGatewayRecentWorkspaceConnectionsView.kt
> Add agent name in workspaces rows + Fetch workspaces resources from latestBuild instead of templateversions api

- src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt
- src/main/kotlin/com/coder/gateway/sdk/CoderRestClient.kt
- src/main/kotlin/com/coder/gateway/views/CoderGatewayRecentWorkspaceConnectionsView.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspacesStepView.kt
Replace the REST-API-based start flow with one that shells out to the coder CLI.
This is the JetBrains extension equivalent to https://github.com/coder/vscode-coder/pull/400.
> Start workspaces by shelling out to CLI

- CHANGELOG.md
- src/main/kotlin/com/coder/gateway/CoderRemoteConnectionHandle.kt
- src/main/kotlin/com/coder/gateway/CoderSettingsConfigurable.kt
- src/main/kotlin/com/coder/gateway/settings/CoderSettings.kt
- src/main/resources/messages/CoderGatewayBundle.properties
This setting controls whether the plugin checks for available backend IDE upgrades (on by default). Turning it off suppresses the prompt to upgrade to a newer version.
> Add "Check for IDE updates" setting

- CHANGELOG.md
- src/main/kotlin/com/coder/gateway/CoderSettingsConfigurable.kt
- src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt
- src/main/kotlin/com/coder/gateway/icons/CoderIcons.kt
- src/main/kotlin/com/coder/gateway/models/WorkspaceAndAgentStatus.kt
- src/main/kotlin/com/coder/gateway/sdk/convertors/InstantConverter.kt
- src/main/kotlin/com/coder/gateway/settings/CoderSettings.kt
- src/test/fixtures/inputs/wildcard.conf
- src/test/kotlin/com/coder/gateway/cli/CoderCLIManagerTest.kt
If a user didn't have a jetbrain's plugin block in their ssh config, we accidentally skipped writing one because before wildcards not having any listed workspaces was equivalent to not having anything to write into the config. This fixes that by checking specifically if the contents of the block are empty.
fixes https://github.com/coder/jetbrains-coder/issues/534
> prevent unintended early return from skipping writing wildcard configs

- CHANGELOG.md
- src/main/kotlin/com/coder/gateway/sdk/CoderRestClient.kt
- src/main/kotlin/com/coder/gateway/sdk/v2/CoderV2RestFacade.kt
- src/main/kotlin/com/coder/gateway/util/LinkHandler.kt
Instead of listing all workspaces matching the filter, get info about the specific workspace the user is trying to connect to. This lets `jetbrains-gateway://` links to others' workspaces work without needing to modify the workspace filter parameter.
> Retrieve workspace directly in link handler when using wildcardSSH feature

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/coder/gateway/models/WorkspaceProjectIDE.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspaceProjectIDEStepView.kt
- src/test/kotlin/com/coder/gateway/models/WorkspaceProjectIDETest.kt
The IDE and Project view will no longer show IDEs that are installed and which are not yet released, but
they have a released version available for download.
Old released IDEs that are installed should not be affected by the list of newer releases.
> fix: skip installed EAP, RC, NIGHTLY and PREVIEW ides from showing if they are superseded

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/coder/gateway/util/Dialogs.kt
- src/main/kotlin/com/coder/gateway/util/LinkHandler.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspaceProjectIDEStepView.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspacesStepView.kt
The value of the `folder` URI parameter is passed to the IDE&Project dialog when handling URIs. The folder value will be rendered instead of the default home folder if the value is not blank.
I've also changed the list of Gateway versions we run the verifier against to include Gateway 2025.1 while excluding some ancient releases.Without this commit the PR will fail to build, the declared snapshots are no longer available in the repository    
-resolves #466
> fix:  pass the folder parameter to the IDE&Project dialog

- CHANGELOG.md
- CONTRIBUTING.md
- gradle.properties
- src/main/kotlin/com/coder/gateway/CoderSettingsConfigurable.kt
- src/main/kotlin/com/coder/gateway/cli/CoderCLIManager.kt
- src/main/kotlin/com/coder/gateway/settings/CoderSettings.kt
- src/main/kotlin/com/coder/gateway/views/steps/CoderWorkspacesStepView.kt
- src/main/resources/messages/CoderGatewayBundle.properties
- src/test/kotlin/com/coder/gateway/cli/CoderCLIManagerTest.kt
- src/test/kotlin/com/coder/gateway/sdk/CoderRestClientTest.kt
- src/test/kotlin/com/coder/gateway/settings/CoderSettingsTest.kt
This PR implements a new configurable option to allow users to disable GPG signature verification for downloaded Coder CLI binaries. This feature provides flexibility for environments where signature verification may not be required or where fallback signature sources are not accessible.
A new option. `disableSignatureVerification` is now available only from the Settings page, with no quick shortcut in the main page to discourage users from quickly disabling this option. The `fallbackOnCoderForSignatures` is hidden/not available for configuration once signature verification is disabled.
Additionally a rough draft for developer facing documentation regarding CLI signature verification was added.
> impl: add support for disabling CLI signature verification

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/coder/gateway/util/TLS.kt
- src/test/kotlin/com/coder/gateway/util/AlternateNameSSLSocketFactoryTest.kt
- src/test/kotlin/com/coder/gateway/util/CoderHostnameVerifierTest.kt
When establishing TLS connections, SNI resolution may fail if the configured altHostname contains `_` or any other characters not allowed by domain name standards (i.e. letters, digits and hyphens).
This change introduces a relaxed SNI resolution strategy which ignores the LDH rules completely. Because this change goes hand in hand with auth. via certificates, I was able to reproduce the issue only via UTs. At this point the official Coder releases supports only auth. via API keys.
- fixes #578
> fix: relaxed SNI hostname resolution

- src/main/kotlin/com/coder/gateway/util/LinkHandler.kt
- src/main/kotlin/com/coder/gateway/util/LinkMap.kt
- src/test/kotlin/com/coder/gateway/util/LinkHandlerTest.kt
Agent name is easier to resolve in jetbrains gateway module and provides more safety.
Reported by customer on Zendesk ticket 4391
> impl: prefer agent name over agent id in URI handler
